blank_issues_enabled: false
contact_links:
  - name: Question or discussion
    url: https://github.com/the-brAIn-lab/archepy/discussions
    about: For usage questions, ideas, and general discussion, please use Discussions instead of opening an issue.
